from .research import RESEARCH_PROMPT_TEMPLATE
from .gtm import GTM_PROMPT_TEMPLATE
from .channel import CHANNEL_PROMPT_TEMPLATE

__all__ = [
    'RESEARCH_PROMPT_TEMPLATE',
    'GTM_PROMPT_TEMPLATE',
    'CHANNEL_PROMPT_TEMPLATE'
]